{{- range .Values.spec }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .image.name }}
  labels:
    {{- with .image.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .image.replicaCount }}
  selector:
    matchLabels:
      {{- with .image.selector.matchLabels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- with .image.selector.matchLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .image.name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9080
              protocol: TCP
{{/*          livenessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /*/}}
{{/*              port: http*/}}
{{/*          readinessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /*/}}
{{/*              port: http*/}}
{{/*          resources:*/}}
{{/*            {{- toYaml .image.resources | nindent 12 }}*/}}
{{- end }}
